server:
  port: 8082
    
# Oracle #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MICROJAVA220822_CLIENTE
    username: root
    password: Peru2021$$.
    driver-class-name: com.mysql.cj.jdbc.Driver

# Registry Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true