
#application:
#  title: Microservicios de Pedidos - Query
#  version: 1.0.0
#  author: Galaxy Training

server:
  port: 8084
    
# MongoDB #
spring:
   data:
      mongodb:
         database: MICROJAVA220822_PEDIDO_QUERY
#        username:
#        password:
         host: localhost
         port: 27017

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true